/**:
  ros__parameters:
    min_longitudinal_offset: 0.01
    max_longitudinal_offset: 0.59
    min_lateral_offset: -0.3
    max_lateral_offset: 0.3
    min_height_offset: 0.08
    max_height_offset: 0.33
