/**:
  ros__parameters:
    wheel_radius: 0.1 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.1 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 0.365 # between front wheel center and rear wheel center
    wheel_tread: 0.437 # between left wheel center and right wheel center
    front_overhang: 0.165 # between front wheel center and vehicle front
    rear_overhang: 0.13 # between rear wheel center and vehicle rear
    left_overhang: 0.076 # between left wheel center and vehicle left
    right_overhang: 0.076 # between right wheel center and vehicle right
    vehicle_height: 0.328
    max_steer_angle: 3.14 # [rad]
